# Generated by Django 5.0.3 on 2024-04-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/image')),
                ('product_counts', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.maincategory')),
            ],
        ),
    ]
