# Generated by Django 5.0.3 on 2024-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=90, null=True)),
                ('title', models.CharField(max_length=90)),
                ('message', models.TextField(max_length=1500)),
            ],
        ),
    ]
