# Generated by Django 5.0.3 on 2024-04-01 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.productfeature')),
            ],
        ),
    ]
