# Generated by Django 5.0.1 on 2024-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userauthcode_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcode',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
